### ISSUE TITLE
x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by Julius112** [SierraSoftworks/minback-cleanup#18]
The application running in the container could not validate the certificate for my Minio instance. I added this fix to install the X509 root certs:

```
From 14f42d2fc17114fc99b99507c5642d7426fa3abb Mon Sep 17 00:00:00 2001
From: Julius Niedworok <julius.niedworok@skillbyte.de>
Date: Wed, 31 Mar 2021 19:46:44 +0200
Subject: [PATCH] fix: adding X509 root certificates to validate minio cert

Signed-off-by: Julius Niedworok <julius.niedworok@skillbyte.de>
---
 Dockerfile | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/Dockerfile b/Dockerfile
index 176f08c..fd4bba1 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -19,7 +19,7 @@ RUN go build -o bin/minback-cleanup -a -installsuffix cgo -ldflags "-s -X main.v
 FROM alpine:latest
 LABEL maintainer="Benjamin Pannell <admin@sierrasoftworks.com>"
 
-RUN apk add --update tini
+RUN apk add --update tini ca-certificates
 ENTRYPOINT ["/sbin/tini", "--"]
 
 COPY --from=0 /go/src/github.com/SierraSoftworks/minback-cleanup/bin/minback-cleanup /bin/minback-cleanup
@@ -34,4 +34,5 @@ ENV MINIO_ACCESS_KEY=""
 ENV MINIO_SECRET_KEY=""
 
 ENTRYPOINT ["/bin/minback-cleanup"]
-CMD ["cleanup"]
\ No newline at end of file
+CMD ["cleanup"]
+
-- 
2.31.1
```

If you give me write access to the repository than I'm happy to create a pull request as well.

Cheers,
Julius

**Comment by notheotherben** [comment]
Thank you for reporting this Julius, I believe you should be able to submit a PR by forking the repository and I've created #19 to include your change, however if you'd prefer to receive the credit, I am more than happy to hold off there and let you submit the PR.

**Comment by Julius112** [comment]
Ahhh yes - the fork worked. I'm actually not used to the github way of doing pull requests. But I've now created a PR to get the credits but also go through the procedure :)
Thanks,
Julius

**Comment by notheotherben** [comment]
That's perfect, thank you so much for the contribution :+1:

**Comment by Julius112** [comment]
You're welcome - I'm happy to help
